DROP DATABASE IF EXISTS dnds_db;
CREATE DATABASE dnds_db;

USE dnds_db;

CREATE TABLE npcs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(25) NOT NULL,
    race VARCHAR(10) NOT NULL,
    eye_color VARCHAR(10) NOT NULL,
    hair_color VARCHAR(10) NOT NULL,
    build VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    personality VARCHAR(20) NOT NULL, 
    profession VARCHAR(20) NOT NULL, 
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE buildings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(25) NOT NULL,
    purpose VARCHAR(10) NOT NULL,
    landLord VARCHAR(20) NOT NULL,
    ofNote VARCHAR(25) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
