DROP DATABASE IF EXISTS dnds_db;
CREATE DATABASE dnds_db;

USE dnds_db;

CREATE TABLE npcs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(10) NOT NULL,
    lastname VARCHAR(10) NOT NULL,
    race VARCHAR(10) NOT NULL,
    eye_color VARCHAR(10) NOT NULL,
    hair_color VARCHAR(10) NOT NULL,
    build VARCHAR(10) NOT NULL,
    age INTEGER NOT NULL,
    personality VARCHAR(10) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);